name: PingPlugin
version: 1.0
main: tamakake.ping.PingPlugin
api-version: 1.20

commands:
  ping:
    description: ping確認
    usage: /ping [player]

permissions:
  tamakake.admin:
    description: 他人のpingを確認できる
    default: op